### ISSUE TITLE
Broken Travis

### ISSUE THREAD

**Issue by eddycek** [keboola/aws-s3-writer#6]
Vytvořil jsem PR a nespustil se travis, viz https://github.com/keboola/aws-s3-writer/pull/5

**Comment by eddycek** [comment]
Zdá se mi že je to vypnuté

<img width="1345" alt="Snímek obrazovky 2019-10-10 v 15 05 46" src="https://user-images.githubusercontent.com/1696274/66594433-89f5df00-eb6f-11e9-9f25-3b8f05e3f05b.png">

cc @ondrejhlavacek

**Comment by ujovlado** [comment]
Kukni sem: https://travis-ci.org/keboola/aws-s3-writer/requests

**Comment by eddycek** [comment]
Jo bylo to vypnuté, zapnul jsem to.

**Comment by eddycek** [comment]
Ach, ale nejsou tam ENV, viz https://travis-ci.org/keboola/aws-s3-writer/builds/596244696?utm_source=github_status&utm_medium=notification

**Comment by ondrejhlavacek** [comment]
Je to asi nějak blbě propojený, běží to na https://travis-ci.com/keboola/aws-s3-writer/builds (`.org` -> `.com`).

**Comment by eddycek** [comment]
Bohužel nejsem owner repositáře, nemohu s tím nic udělat:
- https://travis-ci.com/keboola/aws-s3-writer
- https://travis-ci.org/keboola/aws-s3-writer

Můžeš se na to @ondrejhlavacek podívat, stačí až budeš mít někdy chvilku času. Díky

**Comment by ondrejhlavacek** [comment]
No to je v hajzlu, jsem na `.com` zmáčkl tlačítko migrate a teď je tam totéž co na `.org`.

**Comment by ondrejhlavacek** [comment]
https://travis-ci.com/keboola/aws-s3-writer/builds/131567830 Už to valí

**Comment by eddycek** [comment]
@ondrajodas jsi nejlepší, díky 👍
